name:  libnlp-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - clang # [osx]
  - clangxx #   [osx]
  - cmake =3.19.1
  - make
  - protobuf =3.12.4 # includes Protobuf compiler, C++ headers, Python libraries
  - zlib
  - gtest =1.11.0
  - gmock =1.11.0
  - rapidjson =1.1.0
  - tclap
  - pybind11 = 2.8.0
  - gtest =1.11.0
  - gmock =1.11.0
  - benchmark